## NumPy

In [2]:
my_list = [1,2,3]

In [3]:
my_list

[1, 2, 3]

In [4]:
import numpy as np

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [18]:
range(0,10,2)

range(0, 10, 2)

In [19]:
my = range(10)

In [20]:
list(my)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [28]:
np.linspace(0,5,4)

array([0.        , 1.66666667, 3.33333333, 5.        ])

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
np.random.rand(5)

array([0.25335138, 0.92288368, 0.58339083, 0.87560246, 0.46410823])

In [31]:
np.random.rand(5,5)

array([[0.53291407, 0.43962172, 0.29413149, 0.3038548 , 0.70150864],
       [0.24527919, 0.56887157, 0.25432017, 0.4384197 , 0.00810391],
       [0.9739127 , 0.29276103, 0.06421035, 0.07588558, 0.63490771],
       [0.22791508, 0.45338325, 0.50523686, 0.16888623, 0.09538369],
       [0.56680107, 0.82126754, 0.75577876, 0.48511872, 0.14713351]])

In [34]:
np.random.randn(2,5)

array([[-0.69026069,  0.69370304,  0.18027576, -0.61744099, -0.94437559],
       [-0.36419152,  0.93522834,  0.4174784 , -1.02695845,  1.08470874]])

In [37]:
np.random.randint(0,100,10)

array([91, 95,  8, 90, 66, 10, 56, 50, 17, 97])

In [38]:
arr =np.arange(25)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
ranarr = np.random.randint(0,50,10)

In [41]:
ranarr

array([18, 31, 49, 26, 19, 40, 31, 17, 45, 36])

In [42]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
ranarr.max()

49

In [45]:
ranarr.min()

17

In [46]:
ranarr.argmax()

2

In [47]:
ranarr.argmin()

7

In [48]:
arr.shape

(25,)

In [51]:
arr.shape

(25,)

In [52]:
arr.dtype

dtype('int32')

# NumPy Indexing and Selection

In [2]:
import numpy as np

In [3]:
arr =np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[0]

0

In [6]:
arr[6]

6

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr =np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
slice_of_arr = arr[0:6]

In [15]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
slice_of_arr[:]=99

In [17]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [18]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arr_copy = arr.copy()

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
arr_copy[:] = 100

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [26]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [27]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
arr_2d[0][0]

5

In [29]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
arr_2d[0]

array([ 5, 10, 15])

In [31]:
arr_2d[1][1]

25

In [32]:
arr_2d[2][1]

40

In [33]:
arr_2d[2,1]

40

In [35]:
arr_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [36]:
arr_2d[[0,2]]

array([[ 5, 10, 15],
       [35, 40, 45]])

In [37]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [41]:
arr = np.arange(1,11)

In [42]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [45]:
arr[>5]

SyntaxError: invalid syntax (<ipython-input-45-96f88217121f>, line 1)

In [46]:
arr[arr<3]

array([1, 2])

In [47]:
arr_2d = np.arange(50).reshape(5,10)

In [48]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [51]:
arr_2d[2:4,1:3]

array([[21, 22],
       [31, 32]])

In [52]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

 # NumPy Operations

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
3*arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [8]:
1/0

ZeroDivisionError: division by zero

In [9]:
arr/arr

c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [12]:
arr **5

array([     0,      1,     32,    243,   1024,   3125,   7776,  16807,
        32768,  59049, 100000], dtype=int32)

In [13]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [14]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [15]:
arr.max()

10

In [16]:
arr.max

<function ndarray.max>

In [18]:
arr.argmax()

10

In [19]:
np.max(arr)

10

In [20]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [21]:
np.log(arr)

c:\users\hp\appdata\local\programs\python\python37-32\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])